# name of the workflow, what it is doing (optional)
name: Tracking with pose model test

# events that trigger the workflow (required)
on:
  push:
    # pushes to the following branches
    branches:
      - master
  pull_request:
    # pull request where master is target
    branches:
      - master

jobs:
  test-tracking-with-pose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e . --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Test tracking with pose models
      env:
        IMG: ./assets/MOT17-mini/train/MOT17-02-FRCNN/img1/000001.jpg
      run: python examples/track.py --yolo-model weights/yolov8n-pose.pt --source $IMG --imgsz 320